package com.seckillproject.mapper;

import com.seckillproject.entity.ItemStock;
import org.apache.ibatis.annotations.Param;

public interface ItemStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Dec 06 14:09:31 CST 2019
     */
    int insert(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Dec 06 14:09:31 CST 2019
     */
    int insertSelective(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Dec 06 14:09:31 CST 2019
     */
    ItemStock selectByPrimaryKey(Integer id);

    ItemStock selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Dec 06 14:09:31 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Dec 06 14:09:31 CST 2019
     */
    int updateByPrimaryKey(ItemStock record);

    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}