package com.seckillproject.mapper;

import com.seckillproject.entity.Sequence;

public interface SequenceMapper {

    Sequence getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Dec 07 10:25:27 CST 2019
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Dec 07 10:25:27 CST 2019
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Dec 07 10:25:27 CST 2019
     */
    Sequence selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Dec 07 10:25:27 CST 2019
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Dec 07 10:25:27 CST 2019
     */
    int updateByPrimaryKey(Sequence record);
}